name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.limitlesslag.LimitlessLag
version: ${version}
api-version: 1.13

softdepend:
  - PlaceholderAPI

commands:
  lagreload:
    description: Reloads the plugin
    aliases:
      - limitlesslagreload
    permission: limitlesslag.reload
  lag:
    description: Toggles lag for yourself or the specified player
    aliases:
      - laggy
      - laggify
      - limitlesslag
    permission: limitlesslag.command

permissions:
  limitlesslag.reload:
    description: Allows the player to use /lagreload
  limitlesslag.command:
    description: Allows the player to use /lag
